"""SIH26006 freight-charter optimizer -- HTTP entry point.

Run locally (no editable install; this repo uses plain global Python, not
uv/venv -- see the environment notes in ``docs/plan.md``):

    python -m uvicorn backend.main:app --reload --app-dir "<repo root>"

or, from the repo root directly:

    python -m uvicorn backend.main:app --reload

Interactive API docs (auto-generated by FastAPI from the schemas below) are
served at ``/docs`` once running.

This module is deliberately thin: it validates HTTP input, calls
``opt.quote.quote()`` (the one real computation, fully tested on its own in
``tests/opt/test_quote.py``), and shapes the result for JSON
(``backend.serialize``). No decision logic lives here.
"""
from __future__ import annotations

import asyncio
import json
import sys
from collections.abc import AsyncIterator, Sequence
from datetime import date
from pathlib import Path
from typing import Any, Final, Literal

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SRC = _REPO_ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

import functools

import polars as pl
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, StreamingResponse
from pydantic import BaseModel, Field
from starlette.concurrency import run_in_threadpool

from anchorage.calibrate import MIN_N_FOR_CORRELATION, calibrate_all_ports
from anchorage.render import overlay_path
from anchorage.store import latest_census
from backend.serialize import model_to_json, quote_envelope_to_json
from berth_truth.empirical import WaitInterval, compute_wait_distribution
from berth_truth.fact_port_call import FactPortCallStore
from berth_truth.models import PortId
from berth_truth.reality import PortRealityReport, get_port_reality
from berth_truth.registry import rows_for_port
from berth_truth.sources import PORTWATCH_MAPPING_STATUS
from data_builders.build_geography import PORT_COORDS
from data_builders.harvest_sentinel1 import ANCHORAGE_BOXES
from fragility.engine import analyze_fragility
from fragility.models import VariableId
from fragility.ranking import rank_findings
from ml.live_forecast import forecast_all_classes, latest_available_date
from opt import ledger
from opt.backhaul import BackhaulOpportunityScore, backhaul_opportunity_score
from opt.basis import basis_table_to_entries
from opt.chokepoints import CHOKEPOINT_GEOMETRY, CHOKEPOINT_NAMES
from opt.fracture import ChokepointFracture, route_fracture
from opt.geography import UnknownPortPairError, distance_nm
from opt.landed_cost import (
    COMMODITY_SERIES,
    LandedCostRequest,
    compute_landed_cost,
    usd_inr_rate_as_of,
)
from opt.network import PortEnum, route_family_for_origin
from opt.period_cover import assess_period_cover
from opt.portfolio import efficient_frontier, optimize_portfolio_mix, spot_cost_stats
from opt.quote import (
    InsufficientMarketDataError,
    _cached_route_basis_table,
    quote_envelope,
)
from opt.replay import get_replay_snapshot
from opt.types import (
    CargoParcel,
    OptimizerInputs,
    PortfolioMix,
    ProgressStage,
    Vessel,
    VesselClass,
)
from opt.voyage import _REGISTER_PORT_ID, VoyageScheduleResult, schedule_voyages
from opt.war_risk import listed_areas_on_route, war_risk_premium_usd
from tonnage.field import get_ablation_snapshot, get_snapshot
from tonnage.forward import project_tightness_forward

app = FastAPI(
    title="SIH26006 Freight Charter Optimizer",
    description=(
        "Real-forecast-driven dry-bulk chartering recommendations for SAIL: "
        "rate forecast, LOCK/WAIT timing, vessel-type optimization, port "
        "constraints, and risk flags for one cargo lot."
    ),
    version="1.0.0",
)

# Wide open by default -- this is a hackathon backend meant to be built on
# top of by a teammate's frontend running on a different local port; a real
# deployment would restrict this to the actual frontend origin.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class VesselInput(BaseModel):
    """A real vessel already in hand, echoing ``opt.types.Vessel`` field for
    field, except ``current_port``, which -- like ``origin_port``/``dest_port``
    above -- is a request-ready ``PortEnum`` code string, not an embedded
    object. Optional on ``QuoteRequest``: omitting ``vessels`` entirely still
    prices the cargo lot (rate forecast, LOCK/WAIT, vessel-type
    recommendation, port checks, risk) exactly as before -- only voyage
    scheduling and repositioning have nothing to work with without one."""

    vessel_id: str
    vessel_class: str = Field(..., description="One of: Capesize, Panamax, Supramax, Handysize.")
    current_port: str = Field(..., description="PortEnum code, e.g. 'NEWCASTLE_AU'. See GET /ports.")
    status: Literal["idle", "on_tc", "on_voyage"] = "idle"
    available_from: date
    available_until: date | None = None
    dwt: float = Field(..., gt=0)
    draft_m: float = Field(..., gt=0)
    loa_m: float = Field(..., gt=0)
    beam_m: float = Field(..., gt=0)
    speed_kn: float = Field(..., gt=0)
    laden_fuel_consumption_tpd: float = Field(..., gt=0)
    ballast_fuel_consumption_tpd: float = Field(..., gt=0)


class QuoteRequest(BaseModel):
    cargo_volume_dwt: float = Field(..., gt=0, description="Cargo lot size, in dwt.")
    origin_port: str = Field(..., description="PortEnum code, e.g. 'NEWCASTLE_AU'. See GET /ports.")
    dest_port: str = Field(..., description="PortEnum code, e.g. 'PARADIP'. See GET /ports.")
    laycan_start: date
    laycan_end: date
    contract_term_days: int = Field(30, gt=0)
    commodity: str = "Dry Bulk"
    as_of: date | None = Field(
        None, description="Treat this date as 'today'. Omit to use the latest real market data on disk."
    )
    risk_tolerance: float = Field(0.0, ge=0.0, le=1.0, description="0=risk-neutral, 1=fully risk-averse.")
    vessels: list[VesselInput] | None = Field(
        None,
        description=(
            "Optional real vessels already in hand. Omit for 'what should I do about this cargo' "
            "(the common case); supply vessels to also get real voyage-assignment and "
            "repositioning recommendations against them."
        ),
    )
    revenue_usd: float | None = Field(
        None,
        description=(
            "What this cargo is worth to the caller, for the voyage-assignment optimizer. "
            "No honest default exists (revenue is a business fact, not something a market "
            "forecast can supply) -- without it, a supplied vessel is correctly never assigned "
            "to this cargo, even if otherwise feasible."
        ),
    )


class FragilityRequest(BaseModel):
    """QuoteRequest-shaped, per the P5 API contract -- the fields
    analyze_fragility actually consumes, plus the optional variable subset.
    vessels/revenue_usd are not accepted: analyze_fragility never assigns a
    real vessel (it uses a class-representative one throughout), so there is
    nothing honest for those fields to do here."""

    cargo_volume_dwt: float = Field(..., gt=0)
    origin_port: str
    dest_port: str
    laycan_start: date
    laycan_end: date
    contract_term_days: int = Field(30, gt=0)
    commodity: str = "Dry Bulk"
    as_of: date | None = None
    risk_tolerance: float = Field(0.0, ge=0.0, le=1.0)
    variables: list[str] | None = Field(
        None, description="Subset of VariableId values to search. Omit for all eight."
    )


class OutcomeRequest(BaseModel):
    entry_id: str
    realized_rate_usd_per_day: float = Field(..., gt=0)
    realized_at_date: date
    note: str | None = None


class LandedCostApiRequest(BaseModel):
    """P6: opt.landed_cost.LandedCostRequest, request-shaped (port as a
    code string, per every other endpoint's convention). Every commercial
    term (handling/demurrage/laytime) is optional with no default -- see
    opt.landed_cost's own module docstring for why omitting one means
    unavailable, never a silently-assumed number."""

    dest_port: str = Field(..., description="PortEnum code, e.g. 'PARADIP'. See GET /ports.")
    cargo_volume_mt: float = Field(..., gt=0)
    freight_usd_per_day: float = Field(..., gt=0, description="A real quoted/forecast rate, e.g. from POST /quote's today_quote_usd_per_day.")
    voyage_days: float = Field(..., gt=0)
    vessel_class: str | None = Field(None, description="One of: Capesize, Panamax, Supramax, Handysize. Narrows the empirical wait sample.")
    commodity_class: str | None = None
    opex_usd_per_day: float = Field(0.0, ge=0.0)
    as_of: date | None = None
    handling_rate_usd_per_mt: float | None = Field(None, description="User-declared. No repo-derived default exists -- see opt.landed_cost's module docstring.")
    demurrage_usd_per_day: float | None = Field(None, description="User-declared contractual term. Requires laytime_allowance_days too.")
    laytime_allowance_days: float | None = None
    commodity: str | None = Field(None, description=f"One of: {', '.join(COMMODITY_SERIES)}.")
    convert_to_inr: bool = False
    origin_port: str | None = Field(
        None,
        description=(
            "PortEnum code. Required together with hull_value_usd for the war-risk premium line: "
            "without an origin there is no route, and without a route there is no way to know which "
            "Joint War Committee Listed Areas the voyage enters."
        ),
    )
    hull_value_usd: float | None = Field(
        None, gt=0,
        description=(
            "User-declared insured hull value, for the war-risk premium line. No default exists -- "
            "omitted means the component is unavailable, never a zero line and never an assumed hull."
        ),
    )
    war_risk_rate_pct_per_7_days: float | None = Field(
        None, ge=0,
        description=(
            "Your own quoted additional war-risk rate, as a percentage of hull value per 7-day "
            "transit. Omit to use this system's documented placeholder assumption -- which is NOT a "
            "market rate; see opt.war_risk. The response says which of the two was used."
        ),
    )


class BackhaulRequest(BaseModel):
    """P6: score a vessel's backhaul opportunity at one or more candidate
    load ports after it discharges at discharge_port. Deliberately a
    separate, explicit endpoint, not folded into POST /quote's hot path --
    a real, measured sweep across every port takes several real seconds
    (repeated berth_truth register/hazard lookups per candidate), the same
    reasoning opt.portfolio was kept a separate opt-in function for."""

    vessel: VesselInput
    discharge_port: str = Field(..., description="Where the vessel would discharge before considering a backhaul leg.")
    candidate_load_ports: list[str] | None = Field(
        None,
        description="PortEnum codes to score. Omit to sweep every other real port (slower -- several real seconds).",
    )
    assumed_window_days: int = Field(30, gt=0)


class PortfolioRequest(BaseModel):
    """F-16: opt.portfolio's spot/period-TC/COA coverage-mix optimizer --
    the PS's own stated objective ("moving from multiple single spot
    contracts to short/medium term multiple voyage contracts") -- given a
    real endpoint. Deliberately standalone, not folded into POST /quote:
    the three business inputs below (plant_burden_cover_days,
    stockout_cost_usd, spot_sourcing_hazard_rate_per_day) are real
    SAIL-internal facts this system cannot infer from public market data,
    so this is an explicit, opt-in analysis with those as required fields
    -- never a silently-defaulted guess wearing the shape of real advice."""

    vessel_class: str = Field(..., description="One of: Capesize, Panamax, Supramax, Handysize.")
    contract_term_days: int = Field(..., gt=0, description="The coverage horizon this mix is optimized over, e.g. 180 for a 6-month COA.")
    plant_burden_cover_days: float = Field(..., ge=0, description="Real business input: how many days of buffer stock the plant is carrying.")
    stockout_cost_usd: float = Field(..., ge=0, description="Real business input: the cost of a production stockout.")
    spot_sourcing_hazard_rate_per_day: float = Field(..., ge=0, description="Real business input: how fast SAIL can source spot tonnage, as a daily Poisson rate.")
    risk_aversion_k: float = Field(
        1.0, ge=0,
        description=(
            "How many real spot-cost standard deviations you're willing to pay to avoid, "
            "for the single `recommended` mix. 0 = minimize expected cost only. Scale-free -- "
            "meaningful the same way across any vessel class/term, unlike a raw risk_aversion "
            "weight (which is scenario-specific, since variance is in absolute $^2)."
        ),
    )
    origin_port: str | None = Field(None, description="Optional. If given with dest_port, uses real route-specific rate basis instead of the class benchmark alone -- same as POST /quote.")
    dest_port: str | None = None
    as_of: date | None = None


class FractureRequest(BaseModel):
    """opt.fracture's per-chokepoint disruption index for one real route,
    plus the real Joint War Committee Listed Areas it enters and (when a
    hull value is supplied) an illustrative war-risk premium. See
    opt.fracture's own module docstring for exactly how the index is
    composed and why an incomplete signal set caps its band."""

    origin_port: str = Field(..., description="PortEnum code, e.g. 'NEWCASTLE_AU'. See GET /ports.")
    dest_port: str = Field(..., description="PortEnum code, e.g. 'PARADIP'. See GET /ports.")
    as_of: date | None = Field(None, description="Treat this date as 'today'. Omit to use the latest real market data on disk.")
    hull_value_usd: float | None = Field(
        None, gt=0,
        description=(
            "Real insured hull value, USD. No default exists -- omit it and the response still "
            "reports the route's real Listed Areas, but war_risk_premium is null rather than "
            "priced against an assumed vessel value."
        ),
    )


#: Representative transit speed for the war-risk premium's own transit-day
#: estimate -- POST /fracture takes no vessel, so this is the same 14.0 kn
#: figure every real vessel class in opt.fleetmix._CLASS_SPECS already uses
#: (Handysize through Capesize are all specified at 14.0 kn there), not a
#: figure invented for this endpoint alone.
_FRACTURE_REPRESENTATIVE_SPEED_KN: Final[float] = 14.0


#: The efficient-frontier's own risk_aversion_k grid -- 0 (pure cost
#: minimization) through 8 std devs (very risk-averse), dense enough near 0
#: to catch a real transition (see opt.portfolio module docs) without
#: needing many more than 8 grid-search calls (each is a cheap ~5K-point
#: grid search, not an expensive optimizer -- 8x that is still
#: milliseconds).
_PORTFOLIO_FRONTIER_K: Final[tuple[float, ...]] = (0.0, 0.1, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0)


def _resolve_port(name: str, field: str) -> PortEnum:
    try:
        return PortEnum[name.strip().upper()]
    except KeyError:
        valid = ", ".join(p.name for p in PortEnum)
        raise HTTPException(
            status_code=422, detail=f"Unknown {field} {name!r}. Valid ports: {valid}"
        ) from None


def _resolve_vessel_class(name: str, field: str) -> VesselClass:
    candidate = name.strip()
    for value in (candidate, candidate.capitalize()):
        try:
            return VesselClass(value)
        except ValueError:
            continue
    valid = ", ".join(c.value for c in VesselClass)
    raise HTTPException(status_code=422, detail=f"Unknown {field} {name!r}. Valid classes: {valid}")


def _resolve_vessels(vessels: list[VesselInput] | None) -> list[Vessel] | None:
    if not vessels:
        return None
    return [
        Vessel(
            vessel_id=v.vessel_id,
            vessel_class=_resolve_vessel_class(v.vessel_class, f"vessels[{i}].vessel_class"),
            current_port=_resolve_port(v.current_port, f"vessels[{i}].current_port"),
            status=v.status,
            available_from=v.available_from,
            available_until=v.available_until,
            dwt=v.dwt,
            draft_m=v.draft_m,
            loa_m=v.loa_m,
            beam_m=v.beam_m,
            speed_kn=v.speed_kn,
            laden_fuel_consumption_tpd=v.laden_fuel_consumption_tpd,
            ballast_fuel_consumption_tpd=v.ballast_fuel_consumption_tpd,
        )
        for i, v in enumerate(vessels)
    ]


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/meta")
def meta() -> dict[str, str]:
    """Static facts a client needs to lay out its form -- currently just the
    most recent date the real market data on disk covers, so a "charter as of"
    input can default and cap to it."""
    return {"latest_data_date": latest_available_date().isoformat()}


@app.get("/fx")
def fx_rate(as_of: date | None = None) -> dict[str, object]:
    """The real USD/INR rate, so the desk can display rupees anywhere.

    Rupee display used to be a single checkbox inside the landed-cost panel,
    because that was the only code path that loaded a rate. Making currency a
    desk-wide preference needs the rate desk-wide, and the only honest source
    is the same real series landed_cost already reads: ``MACRO_USD_INR``, the
    FRED DEXINUS observation, forward-filled to the most recent real value on
    or before ``as_of`` and never fabricated before its first observation.

    Returns ``inr_per_usd: null`` with a stated reason rather than a guess when
    no real observation covers the requested date -- the frontend then keeps
    showing dollars instead of inventing a conversion.
    """
    target = as_of or latest_available_date()
    found = usd_inr_rate_as_of(target)
    if found is None:
        return {
            "inr_per_usd": None,
            "as_of": None,
            "provenance": None,
            "reason": f"no real MACRO_USD_INR observation on or before {target.isoformat()}",
        }
    rate, observed_on = found
    return {
        "inr_per_usd": rate,
        "as_of": observed_on.isoformat(),
        "provenance": "OBSERVED",
        "reason": f"FRED DEXINUS, real observation as of {observed_on.isoformat()}",
    }


@app.get("/ports")
def list_ports() -> list[dict[str, object]]:
    """Every real port this system prices, by its request-ready code, with the
    coordinates the route-inspection map plots it at."""
    rows: list[dict[str, object]] = []
    for p in PortEnum:
        loc = PORT_COORDS.get(p.value.id)
        rows.append(
            {
                "code": p.name,
                "name": p.value.id,
                "lat": loc.lat if loc else None,
                "lon": loc.lon if loc else None,
            }
        )
    return rows


@functools.lru_cache(maxsize=512)
def _cached_port_reality(
    port: PortEnum, vessel_draft_m: float, vessel_loa_m: float, vessel_beam_m: float,
    vessel_dwt: float, vessel_class: str | None, vessel_is_laden: bool | None,
    commodity: str | None, as_of: date,
) -> PortRealityReport:
    """P2 §6: 'cache reality reports; do not re-read the register per
    request'. get_port_reality's own FactPortCallStore parameter is
    intentionally not threaded through here -- an lru_cache key must be
    hashable, and the default store (re-opened fresh, cheaply, per call
    inside get_port_reality) is what every real caller uses anyway."""
    return get_port_reality(
        port, vessel_draft_m=vessel_draft_m, vessel_loa_m=vessel_loa_m, vessel_beam_m=vessel_beam_m,
        vessel_dwt=vessel_dwt, vessel_class=vessel_class, vessel_is_laden=vessel_is_laden,
        commodity=commodity, as_of=as_of,
    )


@app.get("/ports/{code}/reality")
def port_reality(
    code: str,
    vessel_dwt: float,
    draft_m: float,
    loa_m: float,
    beam_m: float,
    vessel_class: str | None = None,
    vessel_is_laden: bool | None = None,
    commodity: str = "Dry Bulk",
    as_of: date | None = None,
) -> dict[str, Any]:
    """P2: the M4 Berth Reality Engine's three-state verdict (FEASIBLE /
    INFEASIBLE / CANNOT_VERIFY) for one vessel at one port -- geometry,
    draft, tide authority, empirical wait/handling, observed-vs-declared
    conflicts, all in one real, sourced, dated report."""
    port = _resolve_port(code, "code")
    resolved_as_of = as_of if as_of is not None else latest_available_date()
    report = _cached_port_reality(
        port, draft_m, loa_m, beam_m, vessel_dwt, vessel_class, vessel_is_laden, commodity, resolved_as_of,
    )
    return model_to_json(report)


@app.get("/ports/{code}/berths")
def port_berths(code: str) -> dict[str, Any]:
    """Register rows for this port, with provenance and effective dates --
    an explicit NOT_AVAILABLE payload (never an empty 200 masquerading as
    'no berths exist') for a port with no register entry."""
    port = _resolve_port(code, "code")
    register_port_id: PortId | None = _REGISTER_PORT_ID.get(port)
    if register_port_id is None:
        return {
            "port": port.name, "status": "NOT_AVAILABLE",
            "reason": f"{port.name} has no berth_truth constraint register entry.",
            "berths": [],
        }
    rows = rows_for_port(register_port_id)
    return {"port": port.name, "status": "OK", "berths": [model_to_json(r) for r in rows]}


@app.get("/ports/{code}/calls")
def port_calls(
    code: str, date_from: date | None = None, date_to: date | None = None,
    limit: int = 50, offset: int = 0,
) -> dict[str, Any]:
    """Paginated real fact_port_call rows for this port. NOT_AVAILABLE (not
    an empty 200) when this session's store has genuinely never ingested
    anything for the port, distinguished from a real, empty date-range
    query."""
    port = _resolve_port(code, "code")
    if limit <= 0 or limit > 500:
        raise HTTPException(status_code=422, detail="limit must be between 1 and 500.")
    store = FactPortCallStore()
    all_rows = store.query(port=port, date_from=date_from, date_to=date_to)
    if not all_rows and not store.query(port=port):
        return {"port": port.name, "status": "NOT_AVAILABLE", "total": 0, "rows": []}
    page = all_rows[offset : offset + limit]
    return {
        "port": port.name, "status": "OK", "total": len(all_rows),
        "rows": [model_to_json(r) for r in page],
    }


@app.get("/ports/{code}/waits")
def port_waits(
    code: str, vessel_class: str | None = None, commodity: str | None = None,
) -> dict[str, Any]:
    """Empirical wait distribution (all four real intervals) for this port,
    or an explicit BASELINE_ONLY status when the real sample is too thin --
    never a fabricated percentile."""
    port = _resolve_port(code, "code")
    distributions = {
        interval.value: model_to_json(
            compute_wait_distribution(port, interval, vessel_class=vessel_class, commodity_class=commodity)
        )
        for interval in WaitInterval
    }
    any_sufficient = any(d["is_sufficient"] for d in distributions.values())
    portwatch_status, portwatch_note = PORTWATCH_MAPPING_STATUS.get(port, (None, ""))
    return {
        "port": port.name,
        "status": "OK" if any_sufficient else "BASELINE_ONLY",
        "distributions": distributions,
        "portwatch_mapping_status": portwatch_status.value if portwatch_status else None,
        "portwatch_mapping_note": portwatch_note or None,
    }


# ---------------------------------------------------------------------------
# P3 -- M1 Tonnage Field
# ---------------------------------------------------------------------------


def _latest_on_or_before(df: pl.DataFrame, as_of: date, group_cols: list[str]) -> pl.DataFrame:
    """The latest row per group with date <= as_of -- an as-of read, matching
    the join_asof(strategy="backward") semantics used throughout tonnage/."""
    return df.filter(pl.col("date") <= as_of).sort("date").group_by(group_cols, maintain_order=False).last()


def _sign_diagnosis_json(d: Any) -> dict[str, Any]:
    return {
        "vessel_class": d.vessel_class.value,
        "pearson_r": d.fit.pearson_r,
        "n_obs": d.fit.n_obs,
        "low_confidence": d.fit.low_confidence,
        "weak_signal": d.fit.weak_signal,
        "first_difference": {
            "pearson_r_level": d.first_difference.pearson_r_level,
            "pearson_r_diff": d.first_difference.pearson_r_diff,
        },
        "regime_split": {
            "first_half_r": d.regime_split.first_half_r,
            "second_half_r": d.regime_split.second_half_r,
            "split_date": d.regime_split.split_date.isoformat(),
        },
        "lead_lag": {"by_lag_days": d.lead_lag.by_lag_days, "best_lag_days": d.lead_lag.best_lag_days},
        "basin_aggregation": {
            "pooled_r": d.basin_aggregation.pooled_r,
            "by_basin_r": d.basin_aggregation.by_basin_r,
            "best_basin_beats_pooled": d.basin_aggregation.best_basin_beats_pooled,
        },
        "target_transform": {
            "pearson_r_raw": d.target_transform.pearson_r_raw,
            "pearson_r_log": d.target_transform.pearson_r_log,
        },
        "explanation": d.explanation,
    }


def _landed_cost_to_json(b: Any) -> dict[str, Any]:
    """opt.landed_cost.LandedCostBreakdown, JSON-shaped. Hand-written, not
    the generic model_to_json walk (see backend/serialize.py's own
    docstring on why a raw PortEnum field needs explicit handling) --
    LandedCostBreakdown is a plain dataclass, not a pydantic BaseModel, so
    there is no .model_dump() to reuse here either."""
    return {
        "dest_port": b.dest_port.name,
        "cargo_volume_mt": b.cargo_volume_mt,
        "freight_usd_per_mt": b.freight_usd_per_mt,
        "freight_provenance": b.freight_provenance.value,
        "wait_cost_usd_per_mt": b.wait_cost_usd_per_mt,
        "wait_cost_provenance": b.wait_cost_provenance.value if b.wait_cost_provenance else None,
        "wait_cost_reason": b.wait_cost_reason,
        "wait_p50_hours": b.wait_p50_hours,
        "wait_sample_n": b.wait_sample_n,
        "handling_cost_usd_per_mt": b.handling_cost_usd_per_mt,
        "handling_cost_provenance": b.handling_cost_provenance.value if b.handling_cost_provenance else None,
        "handling_cost_reason": b.handling_cost_reason,
        "demurrage_cost_usd_per_mt": b.demurrage_cost_usd_per_mt,
        "demurrage_cost_provenance": b.demurrage_cost_provenance.value if b.demurrage_cost_provenance else None,
        "demurrage_cost_reason": b.demurrage_cost_reason,
        "war_risk_usd_per_mt": b.war_risk_usd_per_mt,
        "war_risk_provenance": b.war_risk_provenance.value if b.war_risk_provenance else None,
        "war_risk_reason": b.war_risk_reason,
        "war_risk_premium_usd": b.war_risk_premium_usd,
        "war_risk_areas": list(b.war_risk_areas),
        "war_risk_rate_pct_per_7_days": b.war_risk_rate_pct_per_7_days,
        "war_risk_rate_is_caller_supplied": b.war_risk_rate_is_caller_supplied,
        "commodity_price_usd_per_mt": b.commodity_price_usd_per_mt,
        "commodity_price_provenance": b.commodity_price_provenance.value if b.commodity_price_provenance else None,
        "commodity_price_reason": b.commodity_price_reason,
        "commodity_price_raw_value": b.commodity_price_raw_value,
        "commodity_price_raw_unit": b.commodity_price_raw_unit,
        "commodity_price_as_of": b.commodity_price_as_of.isoformat() if b.commodity_price_as_of else None,
        "fx_inr_per_usd": b.fx_inr_per_usd,
        "fx_provenance": b.fx_provenance.value if b.fx_provenance else None,
        "fx_as_of": b.fx_as_of.isoformat() if b.fx_as_of else None,
        "fx_reason": b.fx_reason,
        "components_included": list(b.components_included),
        "components_missing": list(b.components_missing),
        "partial_total_usd_per_mt": b.partial_total_usd_per_mt,
        "partial_total_inr_per_mt": b.partial_total_inr_per_mt,
    }


def _backhaul_score_to_json(r: BackhaulOpportunityScore) -> dict[str, Any]:
    """opt.backhaul.BackhaulOpportunityScore, JSON-shaped -- same reasoning
    as _landed_cost_to_json (a plain dataclass, PortEnum fields need
    explicit .name handling). class_feasibility IS a pydantic model
    (opt.types.FeasibilityVerdict), so .model_dump(mode="json") is reused
    for it via model_to_json rather than hand-shaped field by field."""
    return {
        "vessel_id": r.vessel_id,
        "discharge_port": r.discharge_port.name,
        "candidate_load_port": r.candidate_load_port.name,
        "vessel_class": r.vessel_class,
        "ballast_distance_nm": r.ballast_distance_nm,
        "ballast_days": r.ballast_days,
        "assumed_window_days": r.assumed_window_days,
        "timing_feasible": r.timing_feasible,
        "cargo_probability": r.cargo_probability,
        "cargo_probability_is_real_data": r.cargo_probability_is_real_data,
        "class_feasibility": model_to_json(r.class_feasibility),
        "pairing_evidence": {
            "discharge_port": r.pairing_evidence.discharge_port.name,
            "load_port": r.pairing_evidence.load_port.name,
            "cross_port": r.pairing_evidence.cross_port,
            "n_total_vessels": r.pairing_evidence.n_total_vessels,
            "n_paired_vessels": r.pairing_evidence.n_paired_vessels,
            "load_port_has_coverage": r.pairing_evidence.load_port_has_coverage,
            "pairing_rate": r.pairing_evidence.pairing_rate,
            "is_sufficient": r.pairing_evidence.is_sufficient,
        },
        "score": r.score,
        "ballast_cost_usd": r.ballast_cost_usd,
        "base_tce_usd_per_day": r.base_tce_usd_per_day,
        "score_usd": r.score_usd,
        "credit_usd_per_mt": r.credit_usd_per_mt,
        "credit_evidence_reason": r.credit_evidence_reason,
        "limitations": list(r.limitations),
    }


def _portfolio_mix_to_json(m: PortfolioMix, *, risk_aversion_k: float, risk_aversion: float) -> dict[str, Any]:
    """opt.types.PortfolioMix, JSON-shaped. cost_std_usd is a Python
    @property (sqrt of cost_variance_usd2), not a pydantic field, so
    model_dump() alone would drop it -- added explicitly, it's the number a
    screen actually wants to show (a $ std dev reads; a $^2 variance
    doesn't). risk_aversion_k/risk_aversion travel with each mix since the
    frontier is a list of them at different settings."""
    return {
        "spot_fraction": m.spot_fraction,
        "tc_fraction": m.tc_fraction,
        "coa_fraction": m.coa_fraction,
        "expected_cost_usd": m.expected_cost_usd,
        "cost_std_usd": m.cost_std_usd,
        "stockout_probability": m.stockout_probability,
        "stockout_penalty_usd": m.stockout_penalty_usd,
        "risk_aversion_k": risk_aversion_k,
        "risk_aversion": risk_aversion,
    }


@app.get("/tonnage-field")
def tonnage_field(as_of: date | None = None) -> dict[str, Any]:
    """M1 Tonnage Field: current tightness by class (pooled) and by basin x
    class, the identification-gate verdict, and evidence quality -- cached
    (tonnage.field.get_snapshot), so only the first call after process start
    pays the real reconstruction cost."""
    snap = get_snapshot()
    resolved_as_of = as_of if as_of is not None else snap.tightness["date"].max()

    by_class = _latest_on_or_before(snap.tightness, resolved_as_of, ["vessel_class"])
    by_basin_class = _latest_on_or_before(snap.basin_tightness, resolved_as_of, ["basin", "vessel_class"])
    fits_by_class = {cls.value: fit for cls, fit in snap.fits.items()}

    return {
        "as_of": resolved_as_of.isoformat(),
        "index_type": snap.gate.index_type.value,
        "index_type_reasoning": snap.gate.reasoning,
        "calibration_factor_applied": snap.gate.calibration_factor_applied,
        "computed_at": snap.computed_at.isoformat(),
        "compute_seconds": snap.compute_seconds,
        "stale": snap.stale,
        "evidence_quality": {
            "n_ports_used": snap.result.n_ports_used,
            "n_ports_skipped": snap.result.n_ports_skipped,
            "clipped_fraction": snap.result.clipped_fraction,
            "signal_validation": {
                "n_points": snap.gate.signal_validation.n_points,
                "min_ratio": snap.gate.signal_validation.min_ratio,
                "median_ratio": snap.gate.signal_validation.median_ratio,
                "max_ratio": snap.gate.signal_validation.max_ratio,
                "absolute_scale_validated": snap.gate.signal_validation.absolute_scale_validated,
            },
        },
        "tightness_by_class": [
            {
                "vessel_class": row["vessel_class"],
                "tightness": row["tightness"],
                "n_obs": fits_by_class[row["vessel_class"]].n_obs if row["vessel_class"] in fits_by_class else None,
                "low_confidence": fits_by_class[row["vessel_class"]].low_confidence if row["vessel_class"] in fits_by_class else None,
            }
            for row in by_class.sort("vessel_class").to_dicts()
        ],
        "tightness_by_basin_class": [
            {"basin": row["basin"], "vessel_class": row["vessel_class"], "tightness": row["tightness"]}
            for row in by_basin_class.sort(["vessel_class", "basin"]).to_dicts()
        ],
    }


@app.get("/tonnage-field/forward")
def tonnage_field_forward(horizon: int = 90) -> dict[str, Any]:
    """Forward TIGHTNESS INDEX (P3 requirement 5) -- p10/p50/p90 by class over
    the requested horizon, explicitly labelled RELATIVE. Cheap: computed
    on-demand from the cached snapshot's tightness index (no re-reconstruction)."""
    if horizon <= 0 or horizon > 365:
        raise HTTPException(status_code=422, detail="horizon must be between 1 and 365 days.")
    snap = get_snapshot()
    projection = project_tightness_forward(snap.tightness, horizon_days=horizon)
    return {
        "as_of_date": projection.as_of_date.isoformat(),
        "index_type": projection.index_type,
        "trend_window_days": projection.trend_window_days,
        "computed_at": snap.computed_at.isoformat(),
        "stale": snap.stale,
        "projections": projection.frame.sort(["vessel_class", "horizon_days"]).to_dicts(),
    }


@app.get("/tonnage-field/validation")
def tonnage_field_validation() -> dict[str, Any]:
    """Holdout validation per class + the ablation result (P3 requirements 6
    and 7). The ablation snapshot is cached separately from the main
    reconstruction (tonnage.field.get_ablation_snapshot) -- the first call
    after process start pays the real ~45s A/B XGBoost training cost;
    subsequent calls are warm."""
    snap = get_snapshot()
    ablation_snap = get_ablation_snapshot()
    report = ablation_snap.report

    return {
        "computed_at": snap.computed_at.isoformat(),
        "index_type": snap.gate.index_type.value,
        "iv_verdict": {
            "status": snap.iv_verdict.status.value,
            "candidate_instruments_considered": list(snap.iv_verdict.candidate_instruments_considered),
            "reason": snap.iv_verdict.reason,
        },
        "kalman_verdict": {
            "status": snap.kalman_verdict.status.value,
            "implemented_alternative": snap.kalman_verdict.implemented_alternative,
            "reason": snap.kalman_verdict.reason,
        },
        "sign_diagnoses": [_sign_diagnosis_json(d) for d in snap.sign_diagnoses.values()],
        "ablation": {
            "computed_at": ablation_snap.computed_at.isoformat(),
            "compute_seconds": ablation_snap.compute_seconds,
            "stale": ablation_snap.stale,
            "m1_valid_coverage": report.feature_valid_coverage,
            "m1_test_coverage": report.feature_test_coverage,
            "test_pooled_mean_relative_improvement": report.test_pooled_mean_relative_improvement,
            "valid_pooled_mean_relative_improvement": report.valid_pooled_mean_relative_improvement,
            "adopt_b": report.adopt_b,
            "reasoning": report.reasoning,
            "rows": [r.__dict__ for r in report.rows],
        },
    }


def _quote_partial_landed_cost(quote: Any) -> dict[str, Any] | None:
    """P6: auto-computed, assumption-free slice of opt.landed_cost for
    POST /quote's response -- freight, from the quote's own real forecast
    and transit-day estimate. `None` when opt.present couldn't get a real
    transit-day estimate for this route (the same condition that makes
    ``QuoteResult.today_quote_usd_per_mt`` itself ``None``) -- there is then
    nothing real to convert $/day into $/MT with.

    Wait cost is deliberately NOT computed here even though
    opt.landed_cost.compute_landed_cost would happily return a number:
    QuoteRequest carries no per-vessel opex_usd_per_day, and passing 0.0
    would silently zero out a real, sufficient empirical wait estimate --
    reading as "we checked, it's negligible" instead of the true "we don't
    know your opex." Handling/demurrage/commodity/FX need commercial terms
    QuoteRequest doesn't carry either. See POST /landed-cost for the full,
    assumption-informed breakdown."""
    if quote.assumed_transit_days is None:
        return None
    breakdown = compute_landed_cost(LandedCostRequest(
        dest_port=quote.dest_port, cargo_volume_mt=quote.cargo_volume_dwt,
        freight_usd_per_day=quote.today_quote_usd_per_day, voyage_days=quote.assumed_transit_days,
        vessel_class=quote.target_vessel_class, commodity_class=quote.commodity, as_of=quote.as_of,
    ))
    from dataclasses import replace

    real_wait_cost = breakdown.wait_cost_usd_per_mt or 0.0
    missing = [c for c in breakdown.components_missing]
    if "wait_cost" not in missing:
        missing.append("wait_cost")
    honest = replace(
        breakdown,
        wait_cost_usd_per_mt=None, wait_cost_provenance=None,
        wait_cost_reason="opex_usd_per_day is not available at the /quote level -- see POST /landed-cost.",
        components_included=tuple(c for c in breakdown.components_included if c != "wait_cost"),
        components_missing=tuple(missing),
        partial_total_usd_per_mt=breakdown.partial_total_usd_per_mt - real_wait_cost,
        partial_total_inr_per_mt=(
            (breakdown.partial_total_usd_per_mt - real_wait_cost) * breakdown.fx_inr_per_usd
            if breakdown.fx_inr_per_usd is not None else None
        ),
    )
    return _landed_cost_to_json(honest)


def _run_quote_envelope(req: QuoteRequest, on_progress=None) -> dict[str, Any]:
    """Shared body for ``POST /quote`` and ``POST /quote/stream``: resolve the
    request, run ``quote_envelope``, JSON-shape it. Raises HTTPException for a
    malformed request or missing real data, exactly as before."""
    origin = _resolve_port(req.origin_port, "origin_port")
    dest = _resolve_port(req.dest_port, "dest_port")
    if req.laycan_end < req.laycan_start:
        raise HTTPException(
            status_code=422,
            detail=f"laycan_end ({req.laycan_end}) is before laycan_start ({req.laycan_start}).",
        )
    vessels = _resolve_vessels(req.vessels)
    try:
        envelope = quote_envelope(
            cargo_volume_dwt=req.cargo_volume_dwt,
            origin_port=origin,
            dest_port=dest,
            laycan_start=req.laycan_start,
            laycan_end=req.laycan_end,
            contract_term_days=req.contract_term_days,
            commodity=req.commodity,
            as_of=req.as_of,
            risk_tolerance=req.risk_tolerance,
            vessels=vessels,
            revenue_usd=req.revenue_usd,
            on_progress=on_progress,
        )
    except InsufficientMarketDataError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    # P5 requirement 6: "on each recommendation store" -- every real, priced
    # quote this endpoint returns (feasible or contingent_infeasible; a
    # structural_infeasible envelope has no .quote to record) becomes a real
    # Live Decision Ledger entry. exercise_boundary is not recorded here:
    # QuoteResult does not currently expose opt.stopping's StoppingResult
    # (see opt.ledger.record_recommendation's own docstring) -- a disclosed
    # gap, not silently worked around.
    if envelope.quote is not None:
        ledger.record_recommendation(envelope.quote, risk_tolerance=req.risk_tolerance)

    payload = quote_envelope_to_json(envelope)
    # P6: additive -- a real, assumption-free partial landed-cost slice
    # (freight only; see _quote_partial_landed_cost) alongside the existing
    # envelope, never replacing anything it already returns.
    if envelope.quote is not None:
        payload["landed_cost"] = _quote_partial_landed_cost(envelope.quote)
    return payload


class SeasonParcel(BaseModel):
    """One cargo lot in a multi-voyage plan. Same shape as a /quote's cargo,
    plus an id so the caller can match a returned assignment back to the lot
    it supplied."""

    parcel_id: str = Field(..., min_length=1, description="Caller's own id for this lot.")
    origin_port: str
    dest_port: str
    commodity: str = "Dry Bulk"
    volume_dwt: float = Field(..., gt=0)
    laycan_start: date
    laycan_end: date
    revenue_usd: float = Field(
        0.0,
        description=(
            "What this lot is worth to the caller. No honest default exists -- revenue is a "
            "business fact, not something a market forecast supplies -- so it defaults to 0, "
            "which correctly means the scheduler will not assign a vessel to it."
        ),
    )


class SeasonPlanRequest(BaseModel):
    parcels: list[SeasonParcel] = Field(..., min_length=1, max_length=30)
    vessels: list[VesselInput] = Field(..., min_length=1)
    as_of: date | None = None
    contract_term_days: int = Field(30, gt=0)
    max_solve_seconds: float = Field(30.0, gt=0, le=120.0)


@app.post("/season-plan")
def post_season_plan(req: SeasonPlanRequest) -> dict:
    """Schedule a whole book of cargo lots across a fleet, in one solve.

    The problem statement this system was built for asks for **multiple**
    voyages -- the point of moving off single spot fixtures is covering a
    season with period tonnage. `opt.voyage.schedule_voyages` has always
    solved exactly that: it is a CP-SAT pickup-and-delivery model over
    `inputs.parcels` (plural) and `inputs.vessels`, maximising fleet profit
    net of fuel, idle opex and demurrage, and it has been exercised by the
    suite since it was written.

    Nothing exposed it. `opt.quote.run_quote` builds a single
    `CargoParcel(parcel_id="quote_parcel")` and passes `parcels=[parcel]`, so
    every caller has only ever seen the one-lot case of a many-lot solver.
    This endpoint passes the caller's real lots straight through.

    Deliberately NOT a wrapper that calls /quote N times: scheduling six lots
    together is a different problem from pricing six lots separately, because
    the same vessel cannot serve two overlapping laycans and only a joint
    solve can see that. The rejections it returns are therefore real
    constraint findings, not per-lot failures.

    Returns HTTP 200 with the solver's own status. `NO_DATA` and an empty
    assignment list is a legitimate answer -- it means no vessel can serve any
    lot -- and is reported rather than dressed up.
    """
    as_of = req.as_of or latest_available_date()
    vessels = _resolve_vessels(req.vessels) or []

    parcels: list[CargoParcel] = []
    for i, p in enumerate(req.parcels):
        origin = _resolve_port(p.origin_port, f"parcels[{i}].origin_port")
        dest = _resolve_port(p.dest_port, f"parcels[{i}].dest_port")
        if p.laycan_end < p.laycan_start:
            raise HTTPException(
                status_code=422,
                detail=f"parcels[{i}]: laycan_end {p.laycan_end} is before laycan_start {p.laycan_start}.",
            )
        parcels.append(
            CargoParcel(
                parcel_id=p.parcel_id,
                origin_port=origin,
                dest_port=dest,
                commodity=p.commodity,
                volume_dwt=p.volume_dwt,
                laycan_start=p.laycan_start,
                laycan_end=p.laycan_end,
                route_family=route_family_for_origin(origin),
                revenue_usd=p.revenue_usd,
            )
        )

    ids = [p.parcel_id for p in req.parcels]
    if len(set(ids)) != len(ids):
        raise HTTPException(status_code=422, detail="parcel_id values must be unique.")

    # `schedule_voyages` reads only `parcels` and `vessels` -- it is a routing
    # and sequencing model, not a pricing one, and profit comes from each
    # parcel's own revenue less fuel, idle opex and demurrage. Verified against
    # the function body rather than assumed: it never touches tc_quotes,
    # forecasts, basis or risk_tolerance. Those are supplied empty because
    # OptimizerInputs requires them structurally, not because a real value was
    # unavailable and quietly dropped.
    inputs = OptimizerInputs(
        parcels=parcels,
        vessels=vessels,
        tc_quotes={},
        planning_horizon_days=max(90, req.contract_term_days),
        contract_term_days=req.contract_term_days,
        forecasts=[],
        basis={},
        risk_tolerance=0.0,
    )
    result = schedule_voyages(inputs, max_solve_seconds=req.max_solve_seconds)

    assigned_ids = {a.parcel_id for a in result.assignments}
    return {
        "as_of": as_of.isoformat(),
        "solver_status": result.solver_status,
        "total_profit_usd": result.total_profit_usd,
        "n_parcels": len(parcels),
        "n_vessels": len(vessels),
        "n_assigned": len(result.assignments),
        "assignments": [
            {
                "vessel_id": a.vessel_id,
                "parcel_id": a.parcel_id,
                "dest_port": a.dest_port.value.id,
                "arrival_hours": a.arrival_hours,
                "wait_hours": a.wait_hours,
                "start_operation_hours": a.start_operation_hours,
                "finish_hours": a.finish_hours,
                "ballast_hours": a.ballast_hours,
                "inter_cargo_gap_hours": a.inter_cargo_gap_hours,
                "profit_usd": a.profit_usd,
            }
            for a in result.assignments
        ],
        # Lots the solve could not place, and why. A lot with revenue_usd = 0
        # is unassigned by construction, not by constraint, and says so.
        "unassigned": [
            {
                "parcel_id": p.parcel_id,
                "reason": (
                    "No revenue supplied, so assigning a vessel to this lot could never "
                    "improve fleet profit."
                    if p.revenue_usd <= 0
                    else "No feasible vessel-to-lot pairing survived the port and laycan constraints."
                ),
            }
            for p in parcels
            if p.parcel_id not in assigned_ids
        ],
        # (vessel, parcel, reason) triples the port-constraint pre-filter ruled
        # out before the solver ever saw them -- draft, LOA, beam or DWT.
        "infeasible_pairs": [
            {"vessel_id": v, "parcel_id": pid, "reason": why}
            for v, pid, why in result.infeasible_pairs
        ],
        # Whether covering this book is worth the tonnage it consumes, per
        # vessel class. See opt.period_cover for what this deliberately does
        # NOT claim: there is no period charter rate on disk, so nothing here
        # quotes one.
        "period_cover": _period_cover_for_plan(result, vessels, as_of),
    }


def _period_cover_for_plan(
    result: VoyageScheduleResult,
    vessels: Sequence[Vessel],
    as_of: date,
) -> list[dict]:
    """Break-even hire per vessel class for a solved season plan.

    Split by class on purpose. A single break-even across a mixed fleet would
    be compared against one class's spot average, and a Capesize and a
    Supramax earn very different money per day -- the comparison would be
    arithmetically fine and commercially meaningless.

    Idle vessels are counted in each class's ship-days. Chartering in three
    ships and using two still costs three ships' hire, and the whole point of
    this figure is what the programme costs against what it earns.
    """
    if not result.assignments:
        # No voyages means no earnings to break even on. Reporting a
        # break-even of zero here would read as a real market finding rather
        # than as "there is no plan".
        return []

    span_hours = max(a.finish_hours for a in result.assignments)
    if span_hours <= 0:
        return []

    profit_by_vessel = {a.vessel_id: 0.0 for a in result.assignments}
    for a in result.assignments:
        profit_by_vessel[a.vessel_id] += a.profit_usd

    out: list[dict] = []
    for cls in sorted({v.vessel_class for v in vessels}, key=lambda c: c.value):
        members = [v for v in vessels if v.vessel_class == cls]
        profit = sum(profit_by_vessel.get(v.vessel_id, 0.0) for v in members)
        assessment = assess_period_cover(
            total_profit_usd=profit,
            n_vessels=len(members),
            span_hours=span_hours,
            vessel_class=cls.value,
            as_of=as_of,
        )
        out.append(
            {
                "vessel_class": cls.value,
                "n_vessels": len(members),
                "profit_usd": profit,
                **assessment.model_dump(mode="json"),
            }
        )
    return out


@app.post("/quote")
def post_quote(req: QuoteRequest) -> dict:
    """Price one real cargo lot: rate forecast, LOCK/WAIT, vessel-type
    recommendation, port constraints (both ends), risk flags, and every route
    the solver explored.

    Always returns HTTP 200 with a typed envelope:
    ``{"status": "feasible" | "structural_infeasible" | "contingent_infeasible", ...}``.
    A malformed request (bad port/class, non-positive numbers, inverted laycan)
    still returns 422; missing real data still returns 503.
    """
    return _run_quote_envelope(req)


def _sse(event: str, data: object) -> str:
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


@app.post("/quote/stream")
async def post_quote_stream(req: QuoteRequest) -> StreamingResponse:
    """Same result as ``POST /quote``, but streamed as Server-Sent Events: one
    ``stage`` event per pipeline step as it starts and finishes, then a single
    ``result`` event carrying the envelope (or an ``error`` event)."""
    loop = asyncio.get_running_loop()
    queue: asyncio.Queue[tuple[str, object] | None] = asyncio.Queue()

    def on_progress(stage: ProgressStage) -> None:
        loop.call_soon_threadsafe(queue.put_nowait, ("stage", stage.model_dump(mode="json")))

    async def worker() -> None:
        try:
            payload = await run_in_threadpool(_run_quote_envelope, req, on_progress)
            loop.call_soon_threadsafe(queue.put_nowait, ("result", payload))
        except HTTPException as exc:
            loop.call_soon_threadsafe(
                queue.put_nowait, ("error", {"status_code": exc.status_code, "detail": exc.detail})
            )
        except Exception as exc:  # noqa: BLE001 -- surface anything else to the client too
            loop.call_soon_threadsafe(
                queue.put_nowait, ("error", {"status_code": 500, "detail": str(exc)})
            )
        finally:
            loop.call_soon_threadsafe(queue.put_nowait, None)

    async def gen() -> AsyncIterator[str]:
        task = asyncio.create_task(worker())
        try:
            while True:
                item = await queue.get()
                if item is None:
                    break
                event, data = item
                yield _sse(event, data)
        finally:
            await task

    return StreamingResponse(gen(), media_type="text/event-stream")


# ---------------------------------------------------------------------------
# P5 -- Decision Fragility (DF)
# ---------------------------------------------------------------------------


def _resolve_variables(names: list[str] | None) -> list[VariableId] | None:
    if names is None:
        return None
    out = []
    for n in names:
        try:
            out.append(VariableId(n))
        except ValueError:
            valid = ", ".join(v.value for v in VariableId)
            raise HTTPException(status_code=422, detail=f"Unknown fragility variable {n!r}. Valid: {valid}") from None
    return out


@app.post("/fragility")
def post_fragility(req: FragilityRequest) -> dict[str, Any]:
    """Real flip-point sweep against the live engines -- findings[] with
    flip_value | unavailable_reason, tier, evaluations_used, plus a
    fragile/stable ranking so a caller can lead with what matters most for
    this cargo. A full 8-variable sweep is a real, multi-second cost (Tier 3
    escalations are real CP-SAT + LSMC solves); pass `variables` for a
    faster partial sweep."""
    origin = _resolve_port(req.origin_port, "origin_port")
    dest = _resolve_port(req.dest_port, "dest_port")
    if req.laycan_end < req.laycan_start:
        raise HTTPException(
            status_code=422, detail=f"laycan_end ({req.laycan_end}) is before laycan_start ({req.laycan_start})."
        )
    variables = _resolve_variables(req.variables)
    try:
        report = analyze_fragility(
            cargo_volume_dwt=req.cargo_volume_dwt, origin_port=origin, dest_port=dest,
            laycan_start=req.laycan_start, laycan_end=req.laycan_end, contract_term_days=req.contract_term_days,
            commodity=req.commodity, as_of=req.as_of, risk_tolerance=req.risk_tolerance, variables=variables,
        )
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    ranked = rank_findings(report)
    body = model_to_json(report)
    ranked_by_variable = {r.finding.variable.value: (r.category, r.rank, r.fragility_score) for r in ranked}
    for finding_json in body["findings"]:
        category, rank, score = ranked_by_variable[finding_json["variable"]]
        finding_json["fragility_category"] = category
        finding_json["fragility_rank"] = rank
        finding_json["fragility_score"] = score
    return body


# ---------------------------------------------------------------------------
# 3.4 -- Chokepoint Fracture Index + Joint War Committee war-risk premium
# ---------------------------------------------------------------------------


@app.get("/chokepoints")
def get_chokepoints() -> list[dict[str, Any]]:
    """The static chokepoint reference table (id, name, real centre, and the
    documented judgement-call radius that approximates its transit lane --
    see opt.chokepoints's own module docstring for the sourcing and radius
    rule per entry). Cheap and cacheable client-side: this table changes
    only when opt.chokepoints itself is edited, never per-request."""
    return [
        {
            "id": cp_id,
            "name": CHOKEPOINT_NAMES[cp_id],
            "lat": geom.lat,
            "lon": geom.lon,
            "radius_nm": geom.radius_nm,
        }
        for cp_id, geom in CHOKEPOINT_GEOMETRY.items()
    ]


def _war_risk_premium_to_json(premium: Any) -> dict[str, Any]:
    """opt.war_risk.WarRiskPremium, JSON-shaped -- a plain dataclass, same
    reasoning as _landed_cost_to_json (no .model_dump() to reuse)."""
    return {
        "premium_usd": premium.premium_usd,
        "hull_value_usd": premium.hull_value_usd,
        "areas": list(premium.areas),
        "transit_days": premium.transit_days,
        "periods_charged": premium.periods_charged,
        "rate_pct_per_7_days": premium.rate_pct_per_7_days,
        "rate_is_caller_supplied": premium.rate_is_caller_supplied,
        "provenance": premium.provenance.value,
        "basis": premium.basis,
    }


@app.post("/fracture")
def post_fracture(req: FractureRequest) -> dict[str, Any]:
    """opt.fracture's real per-chokepoint disruption index for this route --
    a tuple of ChokepointFracture (one per real chokepoint the route
    crosses, empty when it crosses none), the real Joint War Committee
    Listed Areas it enters, and an illustrative war-risk premium when a hull
    value was supplied (null, never a fabricated figure, otherwise). Never
    a 500 for missing source data -- a chokepoint with no PortWatch/GDELT
    file on disk still returns a real entry with `inputs_available` naming
    the gap; see opt.fracture's own module docstring."""
    origin = _resolve_port(req.origin_port, "origin_port")
    dest = _resolve_port(req.dest_port, "dest_port")
    resolved_as_of = req.as_of if req.as_of is not None else latest_available_date()

    chokepoints: tuple[ChokepointFracture, ...] = route_fracture(origin, dest, resolved_as_of)
    listed_areas = listed_areas_on_route(origin, dest)

    transit_days: float | None = None
    try:
        transit_days = distance_nm(origin.value.id, dest.value.id) / (_FRACTURE_REPRESENTATIVE_SPEED_KN * 24.0)
    except UnknownPortPairError:
        transit_days = None

    premium = None
    if req.hull_value_usd is not None and transit_days is not None:
        result = war_risk_premium_usd(req.hull_value_usd, listed_areas, transit_days)
        if result is not None:
            premium = _war_risk_premium_to_json(result)

    return {
        "origin_port": origin.name,
        "dest_port": dest.name,
        "as_of": resolved_as_of.isoformat(),
        "chokepoints": [model_to_json(c) for c in chokepoints],
        "jwc_listed_areas": list(listed_areas),
        "transit_days": transit_days,
        "war_risk_premium": premium,
    }


# ---------------------------------------------------------------------------
# P5 -- Live Decision Ledger + Historical Model Replay
# ---------------------------------------------------------------------------


@app.get("/ledger/live")
def get_ledger_live(date_from: date | None = None, date_to: date | None = None) -> dict[str, Any]:
    """Real recommendations this system actually made (LIVE_DECISION_LEDGER),
    plus outcomes where known. Starts empty and fills forward -- an empty
    ledger renders as an empty list, honestly, never seeded examples."""
    linked = ledger.entries_with_outcomes(date_from, date_to)
    return {
        "kind": "LIVE_DECISION_LEDGER",
        "total": len(linked),
        "entries": [
            {
                "entry_id": r.entry.entry_id,
                "decision_timestamp": r.entry.decision_timestamp.isoformat(),
                "cargo_volume_dwt": r.entry.cargo_volume_dwt,
                "origin_port": r.entry.origin_port,
                "dest_port": r.entry.dest_port,
                "laycan_start": r.entry.laycan_start.isoformat(),
                "laycan_end": r.entry.laycan_end.isoformat(),
                "contract_term_days": r.entry.contract_term_days,
                "commodity": r.entry.commodity,
                "as_of": r.entry.as_of.isoformat(),
                # P7: risk_tolerance and exercise_boundary_usd_per_day were
                # both real, already-persisted LedgerEntry fields (the
                # former specifically fixed in P5 to round-trip correctly)
                # that this endpoint never actually serialised -- a real,
                # found-by-auditing gap between what's stored and what a
                # caller (and the ledger-page UI) could see.
                "risk_tolerance": r.entry.risk_tolerance,
                "target_vessel_class": r.entry.target_vessel_class,
                "today_quote_usd_per_day": r.entry.today_quote_usd_per_day,
                "lock_action": r.entry.lock_action,
                "alternative_action": r.entry.alternative_action,
                "ceiling_usd_per_day": r.entry.ceiling_usd_per_day,
                "exercise_boundary_usd_per_day": (
                    list(r.entry.exercise_boundary_usd_per_day) if r.entry.exercise_boundary_usd_per_day else None
                ),
                "model_version": r.entry.model_version,
                "data_version": r.entry.data_version,
                "status": "scored" if r.outcome is not None else "pending",
                "outcome": (
                    {
                        "realized_rate_usd_per_day": r.outcome.realized_rate_usd_per_day,
                        "realized_at_date": r.outcome.realized_at_date.isoformat(),
                        "recorded_at": r.outcome.recorded_at.isoformat(),
                        "note": r.outcome.note,
                    }
                    if r.outcome is not None
                    else None
                ),
            }
            for r in linked
        ],
    }


@app.get("/ledger/live/performance")
def get_ledger_live_performance(date_from: date | None = None, date_to: date | None = None) -> dict[str, Any]:
    """Cumulative regret, LOCK-decision correctness, and baseline comparison
    -- computed ONLY from entries with a real linked outcome (pending entries
    excluded, per requirement). Every mean field is honestly None when
    nothing has been scored yet -- an empty ledger reports zero edge, not a
    fabricated one."""
    summary = ledger.compute_performance(date_from, date_to)
    return {
        "kind": "LIVE_DECISION_LEDGER_PERFORMANCE",
        "n_entries_total": summary.n_entries_total,
        "n_pending": summary.n_pending,
        "n_scored": summary.n_scored,
        "mean_realized_regret_usd_per_day": summary.mean_realized_regret_usd_per_day,
        "lock_accuracy": summary.lock_accuracy,
        "mean_savings_vs_always_lock_usd_per_day": summary.mean_savings_vs_always_lock_usd_per_day,
        "mean_savings_vs_always_wait_usd_per_day": summary.mean_savings_vs_always_wait_usd_per_day,
    }


@app.post("/ledger/outcome")
def post_ledger_outcome(req: OutcomeRequest) -> dict[str, Any]:
    """Record a realised outcome against an existing entry -- appended as a
    new, linked record; the original entry is never touched."""
    try:
        outcome = ledger.record_outcome(
            req.entry_id, realized_rate_usd_per_day=req.realized_rate_usd_per_day,
            realized_at_date=req.realized_at_date, note=req.note,
        )
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    return {
        "outcome_id": outcome.outcome_id, "entry_id": outcome.entry_id,
        "recorded_at": outcome.recorded_at.isoformat(),
        "realized_rate_usd_per_day": outcome.realized_rate_usd_per_day,
        "realized_at_date": outcome.realized_at_date.isoformat(), "note": outcome.note,
    }


@app.delete("/ledger/live")
def delete_ledger_live() -> dict[str, Any]:
    """P7/F-38: clear the Live Decision Ledger entirely -- all entries and
    outcomes at once, no selective deletion possible (see
    opt.ledger.reset_ledger's own docstring for why that's a genuinely
    different, safe operation from the per-entry mutation
    opt.ledger.delete_entry/update_entry still always forbid). Exists
    because every real /quote call auto-records here by design, so a
    session of ordinary use or testing had no way to start clean before a
    demo -- verified live as a real gap, not a hypothetical one."""
    removed = ledger.reset_ledger()
    return {"cleared": True, "records_removed": removed}


@app.get("/ledger/replay")
def get_ledger_replay() -> dict[str, Any]:
    """HISTORICAL_MODEL_REPLAY -- genuine backtest over the real frozen test
    split, explicitly and unmistakably labelled retrospective. Kept
    structurally and semantically separate from /ledger/live*: a different
    top-level "kind", different fields, and its own real backtest statistics
    that are never merged with the live ledger's own numbers."""
    snap = get_replay_snapshot()
    return {
        "kind": "HISTORICAL_MODEL_REPLAY",
        "label": snap.label,
        "computed_at": snap.computed_at.isoformat(),
        "compute_seconds": snap.compute_seconds,
        "stale": snap.stale,
        "contract_term_days": snap.contract_term_days,
        "broker_spread": snap.broker_spread,
        "n_test_rows": snap.n_test_rows,
        "calibration": {
            "best_theta": snap.calibration.best_theta,
            "best_sigma_long": snap.calibration.best_sigma_long,
            "best_risk_tolerance": snap.calibration.best_risk_tolerance,
            "calibrated_on": "valid",
        },
        "summaries": [
            {
                "strategy": s.strategy, "vessel_class": s.vessel_class, "n_decisions": s.n_decisions,
                "savings_mean": s.savings_mean, "savings_p10": s.savings_p10, "savings_p50": s.savings_p50,
                "savings_p90": s.savings_p90, "hit_rate": s.hit_rate, "lock_rate": s.lock_rate,
                "decision_value": s.decision_value, "regret": s.regret,
            }
            for s in snap.summaries
        ],
    }


@app.post("/landed-cost")
def post_landed_cost(req: LandedCostApiRequest) -> dict[str, Any]:
    """P6: component-wise landed-cost breakdown -- freight, P2 empirical
    wait cost, handling/demurrage (user-declared only), P4 commodity price
    and FX (real, if the caller asks for them). Every component is
    separately visible with its own provenance; an unavailable one is
    `null`, never folded into a hidden total -- see
    `partial_total_usd_per_mt`'s own field description and
    `components_missing`. Recompute this with different commercial-term
    assumptions any time; nothing here is cached against the request.
    """
    dest = _resolve_port(req.dest_port, "dest_port")
    vessel_class = _resolve_vessel_class(req.vessel_class, "vessel_class") if req.vessel_class else None
    if req.commodity is not None and req.commodity not in COMMODITY_SERIES:
        raise HTTPException(
            status_code=422,
            detail=f"Unknown commodity {req.commodity!r}. Valid: {', '.join(COMMODITY_SERIES)}",
        )
    breakdown = compute_landed_cost(LandedCostRequest(
        dest_port=dest, cargo_volume_mt=req.cargo_volume_mt,
        freight_usd_per_day=req.freight_usd_per_day, voyage_days=req.voyage_days,
        vessel_class=vessel_class, commodity_class=req.commodity_class,
        opex_usd_per_day=req.opex_usd_per_day, as_of=req.as_of,
        handling_rate_usd_per_mt=req.handling_rate_usd_per_mt,
        demurrage_usd_per_day=req.demurrage_usd_per_day, laytime_allowance_days=req.laytime_allowance_days,
        commodity=req.commodity, convert_to_inr=req.convert_to_inr,
        origin_port=_resolve_port(req.origin_port, "origin_port") if req.origin_port else None,
        hull_value_usd=req.hull_value_usd,
        war_risk_rate_pct_per_7_days=req.war_risk_rate_pct_per_7_days,
    ))
    return _landed_cost_to_json(breakdown)


@app.post("/backhaul")
def post_backhaul(req: BackhaulRequest) -> dict[str, Any]:
    """P6: backhaul opportunity score for one vessel against one or more
    candidate load ports after it discharges at `discharge_port`.
    Informational only -- `credit_usd_per_mt` is always `null` today (see
    each result's `credit_evidence_reason`: FactPortCall carries no rate
    field to validate a $/MT credit against, structurally, not a sample-size
    gap). Never moves any recommendation this API makes elsewhere.

    Omitting `candidate_load_ports` sweeps every other real port -- a real,
    measured multi-second operation (repeated berth_truth lookups per
    candidate), which is exactly why this is its own explicit endpoint and
    not folded into POST /quote.
    """
    discharge = _resolve_port(req.discharge_port, "discharge_port")
    # req.vessel is a required field (not Optional), so _resolve_vessels
    # always gets a real 1-element list back here -- no "vessel is None"
    # branch to guard, unlike QuoteRequest's genuinely-optional vessels.
    vessel = _resolve_vessels([req.vessel])[0]

    if req.candidate_load_ports is not None:
        candidates = [_resolve_port(p, "candidate_load_ports") for p in req.candidate_load_ports]
    else:
        candidates = [p for p in PortEnum if p is not discharge]

    # F-18: score_usd needs a real market rate to value cargo_probability
    # against -- today's real TC quote for this vessel's class, the same
    # class-level rate opt.repositioning's recommend_repositioning already
    # uses for the equivalent idle-vessel decision (see opt.backhaul's own
    # module docstring for the disclosed identical-everywhere limitation).
    # Missing for a real reason (no real quote at this date for this class)
    # is passed through as None, not fabricated -- backhaul_opportunity_score
    # then leaves score_usd None too and says why in `limitations`.
    _, quotes = forecast_all_classes(latest_available_date())
    base_tce = quotes.get(vessel.vessel_class)

    results = [
        backhaul_opportunity_score(
            vessel, discharge, port,
            assumed_window_days=req.assumed_window_days, base_tce_usd_per_day=base_tce,
        )
        for port in candidates
    ]
    results.sort(key=lambda r: r.score_usd if r.score_usd is not None else r.score, reverse=True)
    return {
        "vessel_id": vessel.vessel_id,
        "discharge_port": discharge.name,
        "results": [_backhaul_score_to_json(r) for r in results],
    }


@app.post("/portfolio")
def post_portfolio(req: PortfolioRequest) -> dict[str, Any]:
    """F-16: the PS's own stated objective, given a real endpoint --
    ``opt.portfolio.optimize_portfolio_mix``/``efficient_frontier`` (real,
    already tested logic that previously had no way to be called from the
    running product at all). Returns one `recommended` mix at the caller's
    own `risk_aversion_k`, plus an 8-point `frontier` spanning 0 (pure
    cost-minimization) to 8 real spot-cost standard deviations of risk
    aversion -- always both, so a screen can show a single answer and the
    cost/risk tradeoff behind it in one round trip.

    Deliberately standalone, not part of POST /quote's automatic pipeline --
    see PortfolioRequest's own docstring for why (three real business inputs
    this system cannot infer).
    """
    vessel_class = _resolve_vessel_class(req.vessel_class, "vessel_class")
    resolved_as_of = req.as_of if req.as_of is not None else latest_available_date()
    fans_by_class, quotes = forecast_all_classes(resolved_as_of)

    if vessel_class not in quotes or not fans_by_class.get(vessel_class):
        raise HTTPException(
            status_code=503,
            detail=(
                f"No real TC quote/forecast for {vessel_class.value} as of {resolved_as_of} -- "
                "cannot build a portfolio mix. Try a different as_of date."
            ),
        )
    today_quote = quotes[vessel_class]
    forecasts = fans_by_class[vessel_class]

    basis_entry = None
    route_basis_applied = False
    if req.origin_port is not None and req.dest_port is not None:
        origin = _resolve_port(req.origin_port, "origin_port")
        _resolve_port(req.dest_port, "dest_port")  # validated, not otherwise used -- basis keys off origin's route family only, same as opt.quote
        route_family = route_family_for_origin(origin)
        entries = basis_table_to_entries(_cached_route_basis_table())
        basis_entry = entries.get(route_family)
        route_basis_applied = basis_entry is not None

    try:
        spot_cost, spot_std = spot_cost_stats(forecasts, vessel_class, req.contract_term_days, basis_entry)

        def _mix_kwargs(risk_aversion: float) -> dict[str, Any]:
            return {
                "today_quote_usd_per_day": today_quote, "forecasts": forecasts, "vessel_class": vessel_class,
                "contract_term_days": req.contract_term_days, "plant_burden_cover_days": req.plant_burden_cover_days,
                "stockout_cost_usd": req.stockout_cost_usd,
                "spot_sourcing_hazard_rate_per_day": req.spot_sourcing_hazard_rate_per_day,
                "risk_aversion": risk_aversion, "basis": basis_entry,
            }

        recommended_ra = req.risk_aversion_k / spot_std if spot_std > 0 else 0.0
        recommended = optimize_portfolio_mix(**_mix_kwargs(recommended_ra))

        frontier_ras = [k / spot_std if spot_std > 0 else 0.0 for k in _PORTFOLIO_FRONTIER_K]
        frontier = efficient_frontier(
            today_quote_usd_per_day=today_quote, forecasts=forecasts, vessel_class=vessel_class,
            contract_term_days=req.contract_term_days, plant_burden_cover_days=req.plant_burden_cover_days,
            stockout_cost_usd=req.stockout_cost_usd,
            spot_sourcing_hazard_rate_per_day=req.spot_sourcing_hazard_rate_per_day,
            risk_aversion_grid=tuple(frontier_ras), basis=basis_entry,
        )
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    return {
        "vessel_class": vessel_class.value,
        "as_of": resolved_as_of.isoformat(),
        "contract_term_days": req.contract_term_days,
        "today_quote_usd_per_day": today_quote,
        "spot_cost_usd": spot_cost,
        "spot_cost_std_usd": spot_std,
        "route_basis_applied": route_basis_applied,
        "recommended": _portfolio_mix_to_json(recommended, risk_aversion_k=req.risk_aversion_k, risk_aversion=recommended_ra),
        "frontier": [
            _portfolio_mix_to_json(m, risk_aversion_k=k, risk_aversion=ra)
            for m, k, ra in zip(frontier, _PORTFOLIO_FRONTIER_K, frontier_ras)
        ],
    }


# ---------------------------------------------------------------------------
# 4.3 -- Anchorage vessel census (Sentinel-1 SAR spot check) + calibration
# ---------------------------------------------------------------------------


def _resolve_anchorage_port(code: str) -> str:
    """Anchorage port codes are NOT ``opt.network.PortEnum`` members --
    HAY_POINT_AU in particular is outside that core 16-port network (see
    ``data_builders.harvest_sentinel1``'s own docstring) -- so this
    validates against the same five real anchorage labels
    ``ANCHORAGE_BOXES`` defines, not ``_resolve_port``."""
    normalized = code.strip().upper()
    if normalized not in ANCHORAGE_BOXES:
        valid = ", ".join(sorted(ANCHORAGE_BOXES))
        raise HTTPException(status_code=422, detail=f"Unknown anchorage port {code!r}. Valid ports: {valid}")
    return normalized


@app.get("/anchorage/{port_code}/census")
def get_anchorage_census(port_code: str) -> dict[str, Any]:
    """4.3: the latest real Sentinel-1-derived vessel census for this
    anchorage, or a real 404 when no scene has ever been processed for it --
    never a fabricated empty count. This is a MODEL_DERIVED count from a
    real OBSERVED SAR scene (see ``anchorage.detect``'s own module
    docstring), not a live signal -- Sentinel-1's real revisit cadence is
    6-12 days at these ports; the frontend's own staleness indicator is
    mandatory precisely because a satellite count without its age is
    misleading."""
    port = _resolve_anchorage_port(port_code)
    census = latest_census(port)
    if census is None:
        raise HTTPException(
            status_code=404,
            detail=f"No Sentinel-1 scene has been processed for {port} yet.",
        )
    return census.model_dump(mode="json")


@app.get("/anchorage/{port_code}/overlay.png")
def get_anchorage_overlay(port_code: str) -> FileResponse:
    """4.3 follow-up: the real Sentinel-1 crop behind the latest census, with
    a red ring drawn at every real ``Detection`` that was actually counted
    (``anchorage.render.render_detection_overlay``) -- a picture instead of
    a table of centroid pixels. Overlay rendering is a separate, offline
    step from the harvest/detect/store pipeline (not yet wired into one
    committed orchestrator -- see that module's own docstring), so this is
    real 404, never a placeholder image, when nobody has rendered one for
    the CURRENT latest scene yet."""
    port = _resolve_anchorage_port(port_code)
    census = latest_census(port)
    if census is None:
        raise HTTPException(status_code=404, detail=f"No Sentinel-1 scene has been processed for {port} yet.")
    path = overlay_path(port, census.scene_id)
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"No overlay image has been rendered yet for {port}'s current scene ({census.scene_id}).",
        )
    return FileResponse(path, media_type="image/png")


@app.get("/anchorage/calibration")
def get_anchorage_calibration() -> dict[str, Any]:
    """4.3: the real per-port comparison between satellite vessel counts and
    PortWatch's own real daily call-count series -- evidence, never a
    replacement for the live PortWatch-derived congestion signal
    ``opt.congestion``/``opt.risk`` already use. A correlation is included
    only when a port has at least ``min_n_for_correlation`` real paired
    observations; below that, ``spearman_r``/``pearson_r`` are null and
    ``finding`` says why in plain English -- see ``anchorage.calibrate``'s
    own module docstring."""
    results = calibrate_all_ports()
    return {
        "min_n_for_correlation": MIN_N_FOR_CORRELATION,
        "results": [
            {
                "port": r.port,
                "n": r.n,
                "date_from": r.date_range[0].isoformat() if r.date_range else None,
                "date_to": r.date_range[1].isoformat() if r.date_range else None,
                "spearman_r": r.spearman_r,
                "pearson_r": r.pearson_r,
                "mean_abs_diff": r.mean_abs_diff,
                "finding": r.finding,
            }
            for r in results
        ],
    }
